### ISSUE TITLE
- should be OTHER, not Hyph

### ISSUE THREAD

**Issue by DavidNemeskey** [nytud/emMorph#1]
At least according to the Szeged korpusz, a lone `-` should be tagged as `OTHER` (i.e. just returned as-is), not as `[Hyph:Hyph]`. Yet,
```
> -
-	-	0.000000
-	-[Hyph:Hyph]	0.000000

> .
.	.	0.000000

> ,
,	,	0.000000
```

**Comment by novakat** [comment]
Long hyphen is tagged as [Hyph:Hyph] in all positions by the morphology. We have no [OTHER] tag here. If there is a discrepancy then that's an issue with the Szeged corpus, which was to be brought in sync with the annotation returned by emMorph and emLem.
